language: c

before_script:
  - bash ./.travis-install-deps.sh
script:
  - bash ./.travis-build.sh

before_deploy:
  - "rm -f mondemand-*.tar.gz"
  - "make dist"
  - export RELEASE_FILE=$(ls mondemand-*.tar.gz)

deploy:
  provider: releases
  api_key:
    secure: WXthWfebBowGUySYYBqNVGEh3+yrt4f0ZEVb4nX/jD8Qhhh2ePtIylJFSc7VXNPm2HiHhfp8MkR8zmHTj6DV0iKl2rEHotM3zgHzhHFGMtPG3tlX1iTEAM33lsqQADQbnAlPz78pro1sDAod27x27KTckVhrnP1akj9GfTJQJHC4Ye5xkl4owuF/6urvV3hWR2SlNftLLUeVSuhEsiWw9QSFZbJfNKRtm0jq+tsidsqT8m29h6FW17qhYpwe4v8MgsQpuytcmbaj+TjOnVtyba78VdM5miaAN22BlDFLaglLw4S/GOVGBONKA5O80a05+fW4beVWJKqolZxYGgzV1fjm3IpjWGXRULWox4cVOFQj+fPaa3BDf15hkbtRZxwajt+M3TlgfJ1KSq0yE0Uu3bLgJ3xbLwoJa8mHi9Zkwymo8Cyff6GMh4i99DaHLCs+efKvz5F+FIGhXPhvUsBDm4Y4D/7hV+kOvxS/EVDddNckWO2CBOwbWLloRIQ7x2OyQxg0+/RgjjJSH4kXkUu4gZHUcYCDjK5Mj3x9ZBZN5KYFz6eclkY+myul7n3bZ4AP8f2v8gxxI66+RizCgu6RTJI8uN5eRfmVJMOsZxDx+O07F1GVa3mer/AkOSDuyDNcThKUXs2BYHwNVoH1/0nx6xVw2NhW7bqtNHzxX/Nw3uo=
  skip_cleanup: true
  file:
    - "${RELEASE_FILE}"
  on:
    repo: mondemand/mondemand
    tags: true
